### ISSUE TITLE
[suggestion] appropreate User-Agent

### ISSUE THREAD

**Issue by metalefty** [librespeed/speedtest-cli#11]
I'd appreciate if you set appropreate User-Agent in HTTP request like `LibreSpeedCLI/1.0.6` rather than `Go-http-client/1.1`.

**Comment by maddie** [comment]
Sorry, have been busy lately.

Could you please tell me on which endpoint did you see `Go-http-client/1.1` as user agent? I've set user agent in most requests, maybe some of them I've left off.

**Comment by metalefty** [comment]
Oh, I didn't aware that User-Agent is already set.

At least, `example.com` in the following example will receive `Go-http-client/1.1` request.

```
--server-json http://example.com/server-list.json
```

**Comment by maddie** [comment]
Indeed this request was left out, I've added user-agent to it.

Feel free to re-open if you find another one :)

**Comment by metalefty** [comment]
Thanks!

**Comment by metalefty** [comment]
@maddie 

I still see `Go-http-client/1.1` request.

```
git clone https://github.com/librespeed/speedtest-cli
./build.sh
./out/librespeed-cli-freebsd-amd64 --version
librespeed-cli v1.0.7 (built on 2020-07-15 00:47:49 UTC)
https://github.com/librespeed/speedtest-cli
Licensed under GNU Lesser General Public License v3.0
LibreSpeed      Copyright (C) 2016-2020 Federico Dossena
librespeed-cli  Copyright (C) 2020 Maddie Zhan
librespeed.org  Copyright (C)
```

```
out/librespeed-cli-freebsd-amd64 --server-json http://example.com/servers.json
```

I see the following log at server side:
```
[15/Jul/2020:09:46:55 +0900] "GET /temp/inonius.json HTTP/1.1" 200 435 "-" "Go-http-client/1.1"
```

**Comment by maddie** [comment]
That's weird, I can't reproduce this locally, I was running Go backend with an extra log that prints UA of every request:

Client:

```
# the file doesn't exist, but that shouldn't matter, because we're only logging the UA
$ ./librespeed-cli --server-json http://127.0.0.1:8989/1.json
```

Server:

```
2020/07/15 15:36:52 "GET http://127.0.0.1:8989/1.json HTTP/1.1" from 127.0.0.1:57982 - 403 0B in 35.324µs
INFO[0032] UA: librespeed-cli/v1.0.7      <---- this is the extra log I've added in the code
```

The logger is just an extra middleware in the web server:

```
... omitted code ...

	r.Use(func(next http.Handler) http.Handler {
		fn := func(w http.ResponseWriter, r *http.Request) {
			log.Infof("UA: %s", r.UserAgent())
			next.ServeHTTP(w, r)
		}
		return http.HandlerFunc(fn)
	}

... omitted code ...
```

It actually shows `librespeed-cli/v1.0.7` with the prebuilt binary (the one I've uploaded to releases), but that shouldn't matter, because the UA should be read from a variable, even if no compile-time options were given, the UA would just show a slash (`/`) instead of `Go-http-client/1.1` due to missing program name (the `librespeed-cli` part) and version (`v1.0.7` part).

I'm not really sure about what is going on here.

**Comment by metalefty** [comment]
Indeed, I'll have a look again carefully.

**Comment by metalefty** [comment]
It was my misunderstanding. Now it is working perfectly, thanks!
